name: Build OpenWrt Firmware

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target Platform'
        required: true
        default: 'rockchip'
      subtarget:
        description: 'Subtarget Platform'
        required: true
        default: 'armv8'
      profile:
        description: 'Device Profile'
        required: true
        default: 'friendlyarm_nanopi-r2s'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OpenWrt Source
        uses: actions/checkout@v3
        with:
          repository: openwrt/openwrt
          ref: v23.05.0

      - name: Configure Package Feeds
        run: |
          sed -i 's|https://downloads.openwrt.org|https://mirrors.sjtug.sjtu.edu.cn/openwrt|g' feeds.conf.default

      - name: Update Feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Custom Configuration
        run: |
          echo "CONFIG_TARGET_${{ github.event.inputs.target }}=y" >> .config
          echo "CONFIG_TARGET_${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }}=y" >> .config
          echo "CONFIG_TARGET_${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }}_DEVICE_${{ github.event.inputs.profile }}=y" >> .config
          # 在此添加其他所需的配置选项

      - name: Download Package Sources
        run: make download -j$(nproc)

      - name: Compile Firmware
        run: make -j$(nproc) V=s

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt-Firmware
          path: bin/targets/${{ github.event.inputs.target }}/${{ github.event.inputs.subtarget }}/
